print('Olá, seja bem vindo ao meu site!')
print('Estarei lhe redirecionando para nosso sistema')
nome = input('Qual seu nome ?')
idade = input('Quantos anos você tem?')
print('É um grande prazer te conhecer,{}! você está bem velhio hein?! HAHA'.format(nome))
print('Como eu posso lhe ajudar?')
